spring.application.name = hts
spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
spring.datasource.username = postgres
spring.datasource.password = 1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret.key=thisisthesecretkeyievercreatedinmydevelopmentcareer


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a9492a001@smtp-brevo.com
spring.mail.password=bskQYcudKzsQsAw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=busranuraltunbas@hotmail.com

